/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;


import DAO.UserLoginDAO;
import Utils.UserSession;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ACER
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernamefield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passwordfield = new javax.swing.JPasswordField();
        loginbutton = new javax.swing.JButton();
        showpasswordcheck = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        showsignup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titlePanel.setBackground(new java.awt.Color(242, 192, 120));
        titlePanel.setPreferredSize(new java.awt.Dimension(500, 80));
        titlePanel.setLayout(new java.awt.BorderLayout());

        Title.setBackground(new java.awt.Color(254, 93, 38));
        Title.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Title.setForeground(new java.awt.Color(254, 93, 38));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("KKK");
        titlePanel.add(Title, java.awt.BorderLayout.CENTER);

        getContentPane().add(titlePanel, java.awt.BorderLayout.PAGE_START);

        mainPanel.setBackground(new java.awt.Color(250, 237, 202));
        mainPanel.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setBackground(new java.awt.Color(254, 93, 38));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Username:");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 50));

        usernamefield.setBackground(mainPanel.getBackground());
        usernamefield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernamefield.setForeground(java.awt.Color.gray);
        usernamefield.setText("Enter your username here");
        usernamefield.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        usernamefield.setPreferredSize(new java.awt.Dimension(200, 30));
        usernamefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernamefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernamefieldFocusLost(evt);
            }
        });
        usernamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamefieldActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(254, 93, 38));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Password:");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 50));

        passwordfield.setBackground(new java.awt.Color(250, 237, 202));
        passwordfield.setForeground(java.awt.Color.gray);
        passwordfield.setText("Password");
        passwordfield.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        passwordfield.setPreferredSize(new java.awt.Dimension(200, 20));
        passwordfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordfieldFocusLost(evt);
            }
        });
        passwordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfieldActionPerformed(evt);
            }
        });

        loginbutton.setBackground(new java.awt.Color(254, 93, 38));
        loginbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginbutton.setText("LOGIN");
        loginbutton.setBorder(null);
        loginbutton.setPreferredSize(new java.awt.Dimension(100, 40));
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });

        showpasswordcheck.setForeground(java.awt.Color.darkGray);
        showpasswordcheck.setText("Show Password");
        showpasswordcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpasswordcheckActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(254, 93, 38));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Don't have an account?");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 50));

        showsignup.setBackground(mainPanel.getBackground());
        showsignup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showsignup.setForeground(new java.awt.Color(51, 153, 255));
        showsignup.setText("SIGNUP");
        showsignup.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        showsignup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        showsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showsignupActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(showsignup, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showsignup)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showsignup, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(showpasswordcheck)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(usernamefield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(passwordfield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator3))
                            .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLayeredPane1)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usernamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordfield, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showpasswordcheck, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamefieldActionPerformed
        passwordfield.requestFocus();
    }//GEN-LAST:event_usernamefieldActionPerformed

    private void passwordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfieldActionPerformed
        loginbuttonActionPerformed(new java.awt.event.ActionEvent(loginbutton, ActionEvent.ACTION_PERFORMED, "Enter"));
    }//GEN-LAST:event_passwordfieldActionPerformed

    private void passwordfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordfieldFocusGained
        if (String.valueOf(passwordfield.getPassword()).equals("Password")) {
            passwordfield.setText("");
            passwordfield.setForeground(Color.BLACK);
            passwordfield.setEchoChar('\u2022'); // Mask character (•)
        }
    }//GEN-LAST:event_passwordfieldFocusGained

    private void passwordfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordfieldFocusLost
        if (String.valueOf(passwordfield.getPassword()).isEmpty()) {
            passwordfield.setEchoChar((char) 0);
            passwordfield.setText("Password");
            passwordfield.setForeground(Color.GRAY);
        }

    }//GEN-LAST:event_passwordfieldFocusLost

    private void usernamefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernamefieldFocusGained
        if (usernamefield.getText().equals("Enter your username here")) {
            usernamefield.setText("");
            usernamefield.setForeground(Color.BLACK); // Normal text color
        }
    }//GEN-LAST:event_usernamefieldFocusGained

    private void usernamefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernamefieldFocusLost
        if (usernamefield.getText().isEmpty()) {
            usernamefield.setText("Enter your username here");
            usernamefield.setForeground(Color.GRAY); // Placeholder color
        }
    }//GEN-LAST:event_usernamefieldFocusLost

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
            String username = usernamefield.getText().trim();
    char[] passwordChars = passwordfield.getPassword();
    String password = new String(passwordChars);
    
    // Clear the password array immediately
    Arrays.fill(passwordChars, '\0');
    
    // Validate inputs
    if (username.isEmpty() || username.equals("Enter your username here")) {
        JOptionPane.showMessageDialog(this, "Please enter your username", "Error", JOptionPane.ERROR_MESSAGE);
        usernamefield.requestFocus();
        return;
    }
    
    if (password.isEmpty() || password.equals("Password")) {
        JOptionPane.showMessageDialog(this, "Please enter your password", "Error", JOptionPane.ERROR_MESSAGE);
        passwordfield.requestFocus();
        return;
    }
    
    UserLoginDAO userDAO = new UserLoginDAO();
    try {
        String userRole = userDAO.authenticateUser(username, password);
        
        if (userRole != null) {
            JOptionPane.showMessageDialog(this, "Login Successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
            UserSession.setUsername(username);
            UserSession.setRole(userRole);
            
            // Open appropriate panel based on role
            if ("admin".equalsIgnoreCase(userRole)) {
                AdminPanel adminPanel = new AdminPanel();
                adminPanel.setVisible(true);
            } else {
                Homepage main = new Homepage();
                main.setVisible(true);
            }
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Username or Password", 
                "Login Failed", JOptionPane.ERROR_MESSAGE);
            resetPasswordField();
            usernamefield.requestFocus();
        }
    } finally {
        userDAO.closeConnection();
    }


    }//GEN-LAST:event_loginbuttonActionPerformed

    private void showpasswordcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswordcheckActionPerformed
        if (showpasswordcheck.isSelected()) {
            passwordfield.setEchoChar((char) 0); // Show password
        } else {
            passwordfield.setEchoChar('*'); // Hide password (you can use '*' as well)
        }
    }//GEN-LAST:event_showpasswordcheckActionPerformed

    private void showsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showsignupActionPerformed
        // TODO add your handling code here:
        dispose();
        new Signup().setVisible(true);
        
    }//GEN-LAST:event_showsignupActionPerformed

private void resetPasswordField() {
    passwordfield.setText("");
    passwordfield.setEchoChar((char) 0);
    passwordfield.setForeground(Color.GRAY);
    passwordfield.setText("Password");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatDarkLaf());  // Use FlatLaf
        } catch (UnsupportedLookAndFeelException ex) {
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton loginbutton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JCheckBox showpasswordcheck;
    private javax.swing.JButton showsignup;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField usernamefield;
    // End of variables declaration//GEN-END:variables
}
